### ISSUE TITLE
Problems with project function in adapter 2.0.0

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#117]
Since update of the adapter, it seems that the git settings are no longer available and I cannot write specific states of my flows.

A dialogue says that an unexpected error has occurred and I need to specify the git user settings in node red globally. 

Screenshots are available in my thread in the iobroker forum: 
[Node-Red 2.0.0 - keine Systemobjekte u. andere Probleme](https://forum.iobroker.net/topic/34881/node-red-2-0-0-keine-systemobjekte-u-andere-probleme/13)

**Comment by Sineos** [comment]
Same issue here. When comitting, I get the error:

`Your Git client is not configured with a username/email.`

although it is. My second NR instance v1.1.2 is working. Log shows nothing also on debug setting

**Comment by mickym2** [comment]
Any news?

**Comment by mickym2** [comment]
The problem still exists!!!!

**Comment by bjoernbusch** [comment]
When I manually create the .gitconfig file under the iobroker user, the feature seems to work fine. I'm not sure why it has been working fine in previous versions.

**Comment by mickym2** [comment]
So for all - with the great help of @bjoernbusch this issue can closed - with the following workarround:


Here a short description how a .gitconfig file can be created. 

```
sudo -su iobroker

git config --global user.email "mail@maildomain"
git config --global user.name "name"
```
Many thanks to you @bjoernb. I waited for this solution since several months - and that someone comprehends this issue.  

die .gitconfig file looks like this

```
[user]
        email = mail@maildomain
        name = name
```

**Comment by mickym2** [comment]
I reopened - as I guess that the project function should be in fixed in general - even if the solution works pretty well.

**Comment by Apollon77** [comment]
How we should fix it? I'm not sure that it makes sense that we initialize a git thing, or!?

Anyone has a proposal?

**Comment by Sineos** [comment]
I do not really know what is going wrong but on a bare metal Node-Red when creating a project following happens:
- A git repository is initialized and the flow is copied to the git folder
- the file `.config.users.json` is modified in the `.node-red` folder, which contains the git `email` and `name`

`.config.users.json`

```
{
    "_": {
        "editor": {
            "view": {
                "view-grid-size": "20",
                "view-node-status": true,
                "view-show-tips": true,
                "view-snap-grid": true,
                "view-show-grid": true,
                "view-node-show-label": true
            },
            "context": {
                "flowRefresh": false
            }
        },
        "menu-deploymenu-item-flow": false,
        "menu-deploymenu-item-full": true,
        "git": {
            "user": {
                "name": "Sineos",
                "email": "sineos.pub@gmail.com"
            }
        }
    }
}
```

So usually no intervention should be needed.

**Comment by mickym2** [comment]
The solution is in my opinion "simple" - so I do not know if it simple or not. ;) Before version 2 the git configuration seems to be not relevant or a standard config was used - whatever this means (empty name and email). 

Since version 2 it is necessary to specify git user name and email and if modifying the ` .config.users.json` will solve the problem as well. 

The solution should work when the dialogue is filled out. 

So with version 2 and activation of the project function caused the following error: 

`An unexpected error has occurred - specify the git user settings in node red globally.`

So I switched to the global dialog and filled out name and email: 

![screen](https://user-images.githubusercontent.com/58858526/110242781-d9546080-7f57-11eb-8d89-22723d373033.png)

**And the solution should be:** 
If I fill out this dialogue then either  ` .config.users.json`  file should be modified ( I never tested that) - or what works for me is that the 2 commands 

`
git config --global user.email "mail@maildomain"
git config --global user.name "name"`

will be executed or the appropiate **.gitconfig file** in the /home/iobroker directory is created.

At the moment filling out the dialogue - is either not executed or does not perform the appropiate actions.

**Comment by mickym2** [comment]
Hallo Ingo, 

so ich hab die Lösung nochmals reingeschrieben. Nach Ausfüllen des Dialogs muss im Homeverzeichnis des iobrokers (/home/iobroker) das .gitconfig File mit den Angaben aus dem globalen Git Benutzerdialog erstellt werden. 

Gesendet von Mail für Windows 10

Von: Ingo Fischer
Gesendet: Sonntag, 7. März 2021 13:27
An: ioBroker/ioBroker.node-red
Cc: mickym2; State change
Betreff: Re: [ioBroker/ioBroker.node-red] Problems with project function inadapter 2.0.0 (#117)

How we should fix it? I'm not sure that it makes sense that we initialize a git thing, or!?
Anyone has a proposal?

**Comment by lippoliv** [comment]
Still exists. Synology DS918+, iobroker as Docker with this adapter.

https://github.com/ioBroker/ioBroker.node-red/issues/117#issuecomment-772557066 helped me, I used UI to create a "bash terminal" and then run the three commands. After that, it worked fine.

**Comment by mickym2** [comment]
Ok I found the config.users.json. In iobroker it seems that the file is located under:
/opt/iobroker/iobroker-data/node-red

It seems that the git entries are empty in this file. 

I tried to recreate this error, but seems not be possible, if it works once.

So solution may be is either executing the commands when the dialogue is opened or to change the git settings in the config.users.json file under /opt/iobroker/iobroker-data/node-red

**Comment by Apollon77** [comment]
SI in fact would be more a topic for the readme on "how to set up manually"?

**Comment by mickym2** [comment]
Hmm I do not really understand - why it is not possible to execute both commands when the dialogue is filled out by the user or the .gitconfig file is created. 
If this is not possible as original Node Red Code has to be rewritten - then for sure it needs to be a note somewhere how to enable the project function. In this case the necessary steps can be linked into the Node-Red adapter configuration near the option to enable the project function.

In this case in my opinion it would be the best way - if a user activates the project function in the adapters config

![image](https://user-images.githubusercontent.com/58858526/157524793-4337ed5d-c4f9-44fc-8360-c0f38cf12b64.png)

Both fields could be made available in the adapter config page as well 

![image](https://user-images.githubusercontent.com/58858526/157524980-caeeaf21-d71c-44a9-94e0-fde340c365c5.png)

Then if the adapter config is committed both github commands can be executed:

git config --global user.email "mail@maildomain"
git config --global user.name "name"

In this case the dialogue in NodeRed remains still empty - but to use the project function without errors the necessary 
.gitconfig file is created in the iobrokers home directory:

![image](https://user-images.githubusercontent.com/58858526/157527045-05158f8c-2269-4680-9dbb-0d63a710e126.png)
