### ISSUE TITLE
Enhancement to upgrade NodeRed Version to 2.1.x or higher

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.node-red#241]
As the latest Node-Red Adapter Version contains still Node-Red Version 1.3.7 - it would be great, if the next adapter update contains minimum Node-Red Version 2.1.x.

**Comment by mkcologne** [comment]
And please free the nodes(!) for those who worked with nodered before iobroker. 
Also it would be nice to have nodered independent on a separate server.
Thanks.

**Comment by Apollon77** [comment]
@mkcologne Sorry, but what this has to do with this issue? Additionally this would be kind of a "half rewrite" because the whole communication to ioBroker needs to be changed for "stand alone nodes". Feel free to start such a projkect. We are happy to support.

**Comment by mickym2** [comment]
> And please free the nodes(!) for those who worked with nodered before iobroker. Also it would be nice to have nodered independent on a separate server. Thanks.

I agree that this is not part of the request and has nothing to do with the adapter. Your request has been already addressed here:
https://github.com/ioBroker/ioBroker.node-red/issues/124

**Comment by jwiesel** [comment]
Hi everyone,
I created a pull-request to upgrade the adapter to Node-Red 2.1.4.
It contains the updated settings.js structure that has been introduced in version 2.0.
Please feel free to test & merge. :)

**Comment by mickym2** [comment]
So i am testing the version 2.5 of the adapter. I saw some enhancement (the http static is missing. ;) )  -but I have problems with some warnings  and i already removed manually with npm the rbe - but still have the following warnings when starting node-red:

```
2022-01-27 02:01:01.481 - warn: node-red.0 (5236) 27 Jan 02:01:01 - [warn] ------------------------------------------------------
--
2022-01-27 02:01:01.485 - warn: node-red.0 (5236) 27 Jan 02:01:01 - [warn] [node-red-node-rbe/rbe] Der Typ 'rbe' ist bereits von Modul 'node-red' registriert
2022-01-27 02:01:01.487 - warn: node-red.0 (5236) 27 Jan 02:01:01 - [warn] ------------------------------------------------------
27 Jan 02:01:01 - [info] Einstellungsdatei: /opt/iobroker/iobroker-data/node-red/settings.js
```

The same error is in the pallete manager.

![image](https://user-images.githubusercontent.com/58858526/151273790-e17f4f05-63ef-4fb6-b219-be4b1ddc4b48.png)


If i notice additional problems - I will report this here instead of creating new issues.

**Comment by jwiesel** [comment]
You're welcome! :)

I assume NodeRed still shows rbe in the pallette manager as it just has been relabeled. If I click on one of my previously created rbe nodes in my flow, it says it's a filter node. In the node-menu (left-sidebar) it also shows as "filter"

Release Notes NodeRed 2.0

> RBE: Relabelled as 'filter' to make it more discoverable and made part of
> the core palette, rather than as a separate module.
> 

 
As Node-Red 2.2.0 is available in the meantime I updated my open PR to that version already ;-)

**Comment by mickym2** [comment]
I deinstalled all rbe Nodes and it is working fine. The rbe disappeared now as own installation and is only listed under the core nodes - which is fine.

![image](https://user-images.githubusercontent.com/58858526/152609065-3db0ee02-7ec2-41aa-b8e0-0a6e2fefcaed.png)

**Comment by GermanBluefox** [comment]
Done in next version
![image](https://user-images.githubusercontent.com/4582016/157095720-e5b5f7af-1751-4479-9ae5-fd9e4f245043.png)

**Comment by Apollon77** [comment]
Released in 3.0.0
